version: '3.1'

services:
  db:
    image: postgres-backend
    build: ./db
    restart: always
    environment:
      - POSTGRES_USER=peauaio    
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=peaua_db 
    volumes:
      - peauaio_db:/var/lib/postgresql/data
    networks:
      - nginx-proxy

  backend:
    image: lpeaua/peauaio-backend:latest
    build: ./backend
    expose: 
      - 8000
    environment:
      - DEBUG=False
      - SECRET_KEY=supersecret
      - SQL_ENGINE=django.db.backends.postgresql_psycopg2
      - SQL_DATABASE=peaua_db
      - SQL_USER=peauaio
      - SQL_PASSWORD=password
      - SQL_HOST=db
      - SQL_PORT=5432
      - VIRTUAL_HOST=api.peaua.io
      - LETSENCRYPT_HOST=api.peaua.io
      - LETSENCRYPT_EMAIL=lpeaua@gmail.com
    networks:
      - nginx-proxy
    depends_on:
      - db

  frontend:
    image: lpeaua/peauaio-frontend:latest
    build: ./frontend
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=peaua.io,www.peaua.io
      - LETSENCRYPT_HOST=peaua.io
      - LETSENCRYPT_EMAIL=lpeaua@gmail.com
    networks:
      - nginx-proxy
    depends_on:
      - backend
    links:
      - backend

networks:
  nginx-proxy:
    external:
      name: proxy_nginx-proxy

volumes:
  peauaio_db:

