version: '3' 

services:
    nginx-proxy:
        image: jwilder/nginx-proxy:alpine
        restart: "always"
        ports:
         - "80:80" 
         - "443:443"
        networks:
         - nginx-proxy 
        labels:
         - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
        volumes:
         - /var/run/docker.sock:/tmp/docker.sock:ro
         - "nginx-conf:/etc/nginx/conf.d"
         - "nginx-vhost:/etc/nginx/vhost.d"
         - "html:/usr/share/nginx/html"
         - "certs:/etc/nginx/certs:ro"
         - "static:/opt/PeauaWebDev2.0/backend/static"

    letsencrypt-nginx-proxy-companion:
        image: jrcs/letsencrypt-nginx-proxy-companion
        restart: always
        container_name: letsencrypt-nginx-proxy-companion
        volumes:
         - "/var/run/docker.sock:/var/run/docker.sock:ro"
         - "nginx-conf:/etc/nginx/conf.d"
         - "nginx-vhost:/etc/nginx/vhost.d"
         - "html:/usr/share/nginx/html"
         - "certs:/etc/nginx/certs:rw"
        depends_on:
            - nginx-proxy
networks:
    nginx-proxy:

volumes: 
    nginx-conf:
    nginx-vhost:
    html:
    certs:
    static:
